name: Scheduled Workflows
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00
jobs:
  lockfile:
    name: 🔒 Update flake.lock
    runs-on: [self-hosted, nixos]
    steps:
      - name: 🖥️ Checkout git branch
        uses: actions/checkout@v5
      - name: 🎟 Get GitHub App token
        uses: navikt/github-app-token-generator@b96ff604b2300989cd1105e3fad09199fca56681
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: 🔒 Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
          token: ${{ steps.get-token.outputs.token }}
